//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MauiAppFB {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ChallanReport {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChallanReport() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MauiAppFB.ChallanReport", typeof(ChallanReport).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;lrID&quot;: 4,
        ///      &quot;lrNo&quot;: 0,
        ///      &quot;lrDate&quot;: &quot;2025-03-03T00:00:00&quot;,
        ///      &quot;vehicle_No&quot;: null,
        ///      &quot;party_Name&quot;: &quot;VIRAJ TRANSCORP&quot;,
        ///      &quot;consignor_Name&quot;: null,
        ///      &quot;consignee_Name&quot;: null,
        ///      &quot;from_Location&quot;: null,
        ///      &quot;to_Location&quot;: null,
        ///      &quot;product_Name&quot;: null,
        ///      &quot;driver_Name&quot;: &quot;&quot;,
        ///      &quot;supplier_Name&quot;: null,
        ///      &quot;lr_Nostr&quot;: &quot;123456&quot;,
        ///      &quot;lrContainer1&quot;: &quot;CON1&quot;,
        ///      &quot;lrContainer2&quot;: &quot;CON2&quot;,
        ///      &quot;loadWt&quot;: 12,
        ///      &quot;unloadWt&quot;: 0,
        ///      &quot;chargeWt&quot;: 21,
        ///      &quot;frei [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string customJsonSource1_Json {
            get {
                return ResourceManager.GetString("customJsonSource1.Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {&quot;companyId&quot;: 0,
        ///    &quot;companyUpdatedByUserId&quot;: &quot;string&quot;,
        ///    &quot;companyAddedByUserId&quot;: &quot;string&quot;,
        ///    &quot;companyName&quot;: &quot;string&quot;,
        ///    &quot;companyCode&quot;: &quot;string&quot;,
        ///    &quot;companyPrintName&quot;: &quot;string&quot;,
        ///    &quot;companyAddress1&quot;: &quot;string&quot;,
        ///    &quot;companyAddress2&quot;: &quot;string&quot;,
        ///    &quot;companyAddress3&quot;: &quot;string&quot;,
        ///    &quot;companyStateId&quot;: &quot;string&quot;,
        ///    &quot;companyStateCode&quot;: &quot;strin&quot;,
        ///    &quot;companyEmail&quot;: &quot;string&quot;,
        ///    &quot;companyMobile&quot;: &quot;string&quot;,
        ///    &quot;companyTelephone&quot;: &quot;string&quot;,
        ///    &quot;companyWebsite&quot;: &quot;string&quot;,
        ///    &quot;companyFax&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string customJsonSource2_Json {
            get {
                return ResourceManager.GetString("customJsonSource2.Json", resourceCulture);
            }
        }
    }
}
